if game.PlaceId == 16991287194 then
    loadstring(game:HttpGet("https://gist.githubusercontent.com/S0MEONEuKnow/810ff4633810d109a5a782d5478c0464/raw/222e477f6266c3653ae3b4487df52d8a87525230/sewh5.luau"))()
elseif game.PlaceId == 126884695634066 then
    loadstring(game:HttpGet("https://gist.githubusercontent.com/S0MEONEuKnow/6754b812b155e1fa2427dc784b0dd60b/raw/8f7a7e4cce82e7b62bd2b39e6da798b65bc3da67/gag.luau"))()
elseif game.PlaceId == 286090429 then
    loadstring(game:HttpGet("https://raw.githubusercontent.com/S0MEONEuKnow/Exora/refs/heads/main/azertyuiop%5E%24qsdfghjklm%C3%B9*%3Cwxcvbn%2C%3B%3A!/arsenal.lua"))()
end
